from words import Words
Words().create({"id":"1","word_id":"1","word":"hello","phon":"","language":"ENG"})
Words().create({"word_id":"1","word":"bonjour","phon":"","language":"FRA"})
Words().create({"word_id":"1","word":"ciao","phon":"","language":"ITA"})
Words().create({"word_id":"1","word":"hola","phon":"","language":"SPA"})
Words().create({"word_id":"1","word":"hallo","phon":"","language":"GER"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"GRK"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"RUS"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"CHI"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"JPN"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"KOR"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"HEB"})
Words().create({"word_id":"1","word":"hey","phon":"","language":"ARA"})
Cat().create({"name":"&;128423 communication"})
Subject().create({"cat_id":"1","name":"Phrases"})
Subject().create({"cat_id":"1","name":"Gratitude"})
